
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.customoregen.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.NeoForgeRegistries;

import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.customoregen.item.SharddiamondshovelItem;
import net.mcreator.customoregen.item.SharddiamondpickaxeItem;
import net.mcreator.customoregen.item.SharddiamondaxeItem;
import net.mcreator.customoregen.item.DiamondshardItem;
import net.mcreator.customoregen.item.OreBiomeFinderItem;
import net.mcreator.customoregen.item.SharddiamondhelmetItem;
import net.mcreator.customoregen.item.SharddiamondchestplateItem;
import net.mcreator.customoregen.item.SharddiamondleggingsItem;
import net.mcreator.customoregen.item.SharddiamondbootsItem;
import net.mcreator.customoregen.item.SharddiamondpaxelItem;
import net.mcreator.customoregen.CustomOreGenMod;

import java.util.function.Supplier;

public class CustomOreGenModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(Registries.ITEM, CustomOreGenMod.MODID);
	public static final Supplier<Item> DIAMONDSHARD = REGISTRY.register("diamondshard", () -> new DiamondshardItem());

	// Block items - these need to be registered with the same name as the blocks
	public static final Supplier<Item> SHARDDIAMONDBLOCKORE = REGISTRY.register("sharddiamondblockore",
		() -> new BlockItem(CustomOreGenModBlocks.SHARDDIAMONDBLOCKORE.get(), new Item.Properties()));
	public static final Supplier<Item> PUREGOLDENORE = REGISTRY.register("puregoldenore",
		() -> new BlockItem(CustomOreGenModBlocks.PUREGOLDENORE.get(), new Item.Properties()));
	public static final Supplier<Item> DEEPSLATEPUREGOLDENORE = REGISTRY.register("deepslatepuregoldenore",
		() -> new BlockItem(CustomOreGenModBlocks.DEEPSLATEPUREGOLDENORE.get(), new Item.Properties()));
	public static final Supplier<Item> CONCENTRATEDCOALORE = REGISTRY.register("concentratedcoalore",
		() -> new BlockItem(CustomOreGenModBlocks.CONCENTRATEDCOALORE.get(), new Item.Properties()));
	public static final Supplier<Item> DEEPSLATESHARDDIAMONDORE = REGISTRY.register("deepslatesharddiamondore",
		() -> new BlockItem(CustomOreGenModBlocks.DEEPSLATESHARDDIAMONDORE.get(), new Item.Properties()));
	public static final Supplier<Item> DEEPSLATEDIAMONDORE = REGISTRY.register("deepslatediamondore",
		() -> new BlockItem(CustomOreGenModBlocks.DEEPSLATEDIAMONDORE.get(), new Item.Properties()));
	public static final Supplier<Item> LAPISORE = REGISTRY.register("lapisore",
		() -> new BlockItem(CustomOreGenModBlocks.LAPISORE.get(), new Item.Properties()));
	public static final Supplier<Item> DEEPSLATELAPISORE = REGISTRY.register("deepslatelapisore",
		() -> new BlockItem(CustomOreGenModBlocks.DEEPSLATELAPISORE.get(), new Item.Properties()));
	public static final Supplier<Item> REDSTONEORE = REGISTRY.register("redstoneore",
		() -> new BlockItem(CustomOreGenModBlocks.REDSTONEORE.get(), new Item.Properties()));
	public static final Supplier<Item> DEEPSLATEREDSTONEORE = REGISTRY.register("deepslateredstoneore",
		() -> new BlockItem(CustomOreGenModBlocks.DEEPSLATEREDSTONEORE.get(), new Item.Properties()));
	public static final Supplier<Item> COPPERHIGHORE = REGISTRY.register("copperhighore",
		() -> new BlockItem(CustomOreGenModBlocks.COPPERHIGHORE.get(), new Item.Properties()));
	public static final Supplier<Item> COPPERLOWERORE = REGISTRY.register("copperlowerore",
		() -> new BlockItem(CustomOreGenModBlocks.COPPERLOWERORE.get(), new Item.Properties()));
	public static final Supplier<Item> HIGHEMERALDORE = REGISTRY.register("highemeraldore",
		() -> new BlockItem(CustomOreGenModBlocks.HIGHEMERALDORE.get(), new Item.Properties()));
	public static final Supplier<Item> LOWEREMERALDORE = REGISTRY.register("loweremeraldore",
		() -> new BlockItem(CustomOreGenModBlocks.LOWEREMERALDORE.get(), new Item.Properties()));
	public static final Supplier<Item> IRONORE = REGISTRY.register("ironore",
		() -> new BlockItem(CustomOreGenModBlocks.IRONORE.get(), new Item.Properties()));
	public static final Supplier<Item> DEEPSLATEIRONORE = REGISTRY.register("deepslateironore",
		() -> new BlockItem(CustomOreGenModBlocks.DEEPSLATEIRONORE.get(), new Item.Properties()));

	// Start of user code block custom items
	public static final Supplier<Item> ORE_BIOME_FINDER = REGISTRY.register("ore_biome_finder", () -> new OreBiomeFinderItem());

	// Diamond Shard Armor
	public static final Supplier<Item> SHARDDIAMONDHELMET = REGISTRY.register("sharddiamondhelmet", () -> new SharddiamondhelmetItem());
	public static final Supplier<Item> SHARDDIAMONDCHESTPLATE = REGISTRY.register("sharddiamondchestplate", () -> new SharddiamondchestplateItem());
	public static final Supplier<Item> SHARDDIAMONDLEGGINGS = REGISTRY.register("sharddiamondleggings", () -> new SharddiamondleggingsItem());
	public static final Supplier<Item> SHARDDIAMONDBOOTS = REGISTRY.register("sharddiamondboots", () -> new SharddiamondbootsItem());

	// Diamond Shard Paxel
	public static final Supplier<Item> SHARDDIAMONDPAXEL = REGISTRY.register("sharddiamondpaxel", () -> new SharddiamondpaxelItem());
	// End of user code block custom items

	// Tool items
	public static final Supplier<Item> SHARDDIAMONDPICKAXE = REGISTRY.register("sharddiamondpickaxe", () -> new SharddiamondpickaxeItem());
	public static final Supplier<Item> SHARDDIAMONDSHOVEL = REGISTRY.register("sharddiamondshovel", () -> new SharddiamondshovelItem());
	public static final Supplier<Item> SHARDDIAMONDAXE = REGISTRY.register("sharddiamondaxe", () -> new SharddiamondaxeItem());
}
